name = "TrackingFloats"
uuid = "42463b53-f94d-437a-af09-4f1776b5c9b9"
authors = ["Zheng Jia <zheng.jia@control.lth.se> and contributors"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[compat]
julia = "1.8"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
